### ISSUE TITLE
Compiling errors

### ISSUE THREAD

**Issue by peper0ni** [sibvic/mq5-templates#1]
Hi, 
i want test your framework and tried to compile the "EA_Base.mq5" but got a lot compiling errors.
Can you provide a working example (eg.  EA_Base.mq5 with SMA-Stream)?

**Comment by sibvic** [comment]
> 
> 
> Hi,
> i want test your framework and tried to compile the "EA_Base.mq5" but got a lot compiling errors.
> Can you provide a working example (eg. EA_Base.mq5 with SMA-Stream)?

There are two options:
1. You can wait until I have some free time to do that
2. You can request such an EA at [FXCodebase free development service](fxcodebase.com/code/viewforum.php?f=27)

**Comment by sibvic** [comment]
Should be already fixed

**Comment by sudonto** [comment]
i tried to compile but still give me al lot of errors

**Comment by sibvic** [comment]
> 
> 
> i tried to compile but still give me al lot of errors

Any examples?
